config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :people
  root "people#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/detail.rb
class Detail < ApplicationRecord
  belongs_to :person

  validates :email, presence: true
  
end

app/models/person.rb
class Person < ApplicationRecord
  has_one :detail, dependent: :destroy

  validates :name, presence: true

  accepts_nested_attributes_for :detail

  after_create_commit { broadcast_prepend_to 'people' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:edit, :update, :destroy]

  def index
    @people = Person.includes(:detail)
  end

  def new
    @person = Person.new
    @person.build_detail
  end

  def edit
  end

  def create
    @person = Person.new(person_params)
    respond_to do |format|
      if @person.save
        format.turbo_stream {render turbo_stream: turbo_stream.replace('create_person_form', partial: "create_link")}
        format.html { redirect_to people_path, notice: 'Person created.' }
      else
        format.turbo_stream {render turbo_stream: turbo_stream.replace('person_form_error_', partial: 'error', locals: {person: @person})}
        format.html { redirect_to new_person_path, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to people_path }
        format.turbo_stream { render turbo_stream: turbo_stream.replace("person_#{@person.id}", partial: 'person', locals: { person: @person }) }
      else
        format.turbo_stream {render turbo_stream: turbo_stream.replace("person_form_error_#{@person.id}", partial: 'error', locals: {person: @person})}
        format.html { redirect_to edit_person_path, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @person.destroy
        format.turbo_stream { render turbo_stream: turbo_stream.remove("person_#{@person.id}") }
        format.html { redirect_to people_path }
      else
        format.html { redirect_to people_path, notice: @person.errors.full_message }
      end
    end
  end

  private

  def set_person
    @person = Person.find(params[:id])
  end

  def person_params
    params.require(:person).permit(:name, detail_attributes: [:id, :title, :age, :phone, :email])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MasterDetailApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/_create_link.html.erb
<%= turbo_frame_tag "create_person_form" do %>
  <%= link_to 'Create new person', new_person_path, class: 'btn btn-dark' %>
<% end %>

app/views/people/_error.html.erb
<%= turbo_frame_tag "person_form_error_#{person.id}" do %>
  <% if person.errors.any? %>
    <div id="error_explanation">
    <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

    <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>

    </div>
  <% end %>
<% end %>

app/views/people/_form.html.erb
<%= form_with model: person do |form| %>
  
  <%= render partial: 'error', locals: {person: person} %>

  <%= form.fields_for :detail, id: "people_details" do |detail_form| %>

    <div class="field">
      <%= detail_form.label :title %>
      <%= detail_form.text_field :title %>

      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= detail_form.label :email %>
      <%= detail_form.text_field :email %>
    </div>

    <div class="field">
      <%= detail_form.label :age %>
      <%= detail_form.text_field :age %>
    </div>

    <div class="field">
      <%= detail_form.label :phone %>
      <%= detail_form.text_field :phone %>
    </div>

  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
  <% end %>

<%= button_to 'Cancel', people_path, method: :get %>
  

app/views/people/_person.html.erb
<%= turbo_frame_tag "person_#{person.id}" do %>
  <div style='border-style: ridge; padding: 20px;', class='mt-2'>
    <b><%= person.detail.title %></b>&nbsp;<b><%= person.name %></b><br>
    <b><%= person.detail.email %></b><br>
    <b><%= person.detail.age %></b><br>
    <b><%= person.detail.phone %></b><br>

    <div class='mt-2 d-flex'>
      <%= link_to 'Edit', edit_person_path(person), style: 'margin-left: 5px' %>
      <%= link_to 'Delete', person_path(person), data: {turbo_method: :delete}, style: 'margin-left: 5px' %>
    </div>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Edit Person</h1>

<%= turbo_frame_tag "person_#{@person.id}" do %>
  <div style='border-style: ridge; padding: 20px;', class='mt-2'>
    <%= render partial: 'form', locals: {person: @person}  %>
  </div>
<% end %>

app/views/people/index.html.erb
<h1>People</h1>

<%= render partial: 'create_link' %>

<br>

<h2 class='mt-3'>People</h2>

<%= turbo_stream_from 'people' %>

<%= turbo_frame_tag "people" do %>
  <% if @people.any? %>
    <%= render partial: 'person', collection: @people %>
  <% else %>
    <p>No people available</p>
  <% end %>
<% end %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= turbo_frame_tag "create_person_form" do %>
  <%= render partial: 'form', locals: {person: @person} %>
<% end %>